name: Deploy Next.js

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH key authentication
          port: 22
          script: |
            cd ${{ secrets.SERVER_PATH }}
            
            # Pull latest code
            git fetch --all
            git reset --hard origin/main
            
            # Install dependencies & build
            npm install --force
            npm run build

            # Ensure logs folder exists
            mkdir -p logs

            # Start or reload app using PM2
            if pm2 describe "nextjs-website" > /dev/null; then
              pm2 reload ecosystem.config.js --env production
            else
              pm2 start ecosystem.config.js --env production
            fi

            # Save PM2 process list for reboot
            pm2 save
